export const SPINNER_STATUS = 'SPINNER_STATUS';
export const OPEN_ROOMS_MODAL = 'OPEN_ROOMS_MODAL';
export const NEW_ADDED_ROOMS = 'NEW_ADDED_ROOMS';
export const NEW_ACCOMMODATION_INPUT = 'NEW_ACCOMMODATION_INPUT';
export const NEW_ADDED_PHOTOS = 'NEW_ADDED_PHOTOS';
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS';
export const CREATE_ACCOMMODATION_SUCCESS = 'CREATE_ACCOMMODATION_SUCCESS';
export const CREATE_ACCOMMODATION_ERROR = 'CREATE_ACCOMMODATION_ERROR';

export const GET_MOST_TRAVELLED_SUCCESS = 'GET_MOST_TRAVELLED_SUCCESS';
export const GET_MOST_TRAVELLED_ERROR = 'GET_MOST_TRAVELLED_ERROR';
export const VIEW_ALL_ACCOMMODATION_SUCCESS = 'VIEW_ALL_ACCOMMODATION_SUCCESS';
export const VIEW_ALL_ACCOMMODATION_ERROR = 'VIEW_ALL_ACCOMMODATION_ERROR';
export const VIEW_ALL_LIKES_SUCCESS = 'VIEW_ALL_LIKES_SUCCESS';
export const VIEW_ALL_LIKES_ERROR = 'VIEW_ALL_LIKES_ERROR';

export const LIKES_SUCCESS = 'LIKES_SUCCESS';
export const DISLIKES_SUCCESS = 'DISLIKES_SUCCESS';
export const LIKE_AND_DISLIKES_ERROR = 'LIKE_AND_DISLIKES_ERROR';
export const VIEW_SINGLE_ACCOMMODATION_SUCCESS = 'VIEW_SINGLE_ACCOMMODATION_SUCCESS';
export const VIEW_SINGLE_ACCOMMODATION_ERROR = 'VIEW_SINGLE_ACCOMMODATION_ERROR';

export const VIEW_USER_PROFILE_SUCCESS = 'VIEW_USER_PROFILE_SUCCESS';
export const VIEW_USER_PROFILE_ERROR = 'VIEW_USER_PROFILE_ERROR';
