export const SPINNER_STATUS = 'SPINNER_STATUS';
export const OPEN_ROOMS_MODAL = 'OPEN_ROOMS_MODAL';
export const NEW_ADDED_ROOMS = 'NEW_ADDED_ROOMS';
export const NEW_ACCOMMODATION_INPUT = 'NEW_ACCOMMODATION_INPUT';
export const NEW_ADDED_PHOTOS = 'NEW_ADDED_PHOTOS';
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS';
export const CREATE_ACCOMMODATION_SUCCESS = 'CREATE_ACCOMMODATION_SUCCESS';
export const CREATE_ACCOMMODATION_ERROR = 'CREATE_ACCOMMODATION_ERROR';
