export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_INPUT = 'SIGNUP_INPUT';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_INPUT = 'SIGNIN_INPUT';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';
export const UPDATE_SPINNER_STATUS = 'UPDATE_SPINNER_STATUS';
