export const GET_ALL_BOOKINGS_SUCCESS = 'GET_ALL_BOOKINGS_SUCCESS';
export const GET_ALL_BOOKINGS_ERROR = 'GET_ALL_BOOKINGS_ERROR';
export const OPEN_SINGLE_BOOKING = 'OPEN_SINGLE_BOOKING';
export const GET_SINGLE_BOOKINGS_SUCCESS = 'GET_SINGLE_BOOKINGS_SUCCESS';
export const GET_SINGLE_BOOKINGS_ERROR = 'GET_SINGLE_BOOKINGS_ERROR';
