export const GET_STATS_TRIP_SUCCESS = 'GET_STATS_TRIP_SUCCESS';
export const GET_STATS_TRIP_ERROR = 'GET_STATS_TRIP_ERROR';

export const GET_STATS_INPUT = 'GET_STATS_INPUT';
export const UPDATE_SPINNER_STATUS = 'UPDATE_SPINNER_STATUS';
export const TRIP_COUNTER_INPUT = 'TRIP_COUNTER_INPUT';
