export const GET_ALL_NOTIFICATIONS_SUCCESS = 'GET_ALL_NOTIFICATIONS_SUCCESS';
export const GET_ALL_NOTIFICATIONS_ERROR = 'GET_ALL_NOTIFICATIONS_ERROR';

export const NEW_NOTIFICATION = 'NEW_NOTIFICATION';

export const MARK_ALL_AS_READ_SUCCESS = 'MARK_ALL_AS_READ_SUCCESS';
export const MARK_ALL_AS_READ_ERROR = 'MARK_ALL_AS_READ_ERROR';

export const MARK_ONE_AS_READ_SUCCESS = 'MARK_ONE_AS_READ_SUCCESS';
export const MARK_ONE_AS_READ_ERROR = 'MARK_ONE_AS_READ_ERROR';

export const SPINNER_STATUS = 'SPINNER_STATUS';
