export const RATE_ACCOMMODATION_SUCCESS = 'RATE_ACCOMMODATION_SUCCESS';
export const RATE_ACCOMMODATION_ERROR = 'RATE_ACCOMMODATION_ERROR';

export const ADD_ACCOMMODATION_RATE_INPUT = 'ADD_ACCOMMODATION_RATE_INPUT';
