export const CREATE_ROUND_TRIP_SUCCESS = 'CREATE_ROUND_TRIP_SUCCESS';
export const CREATE_ROUND_TRIP_ERROR = 'CREATE_ROUND_TRIP_ERROR';

export const SPINNER_STATUS = 'SPINNER_STATUS';

export const GET_ALL_CITIES_SUCCESS = 'GET_ALL_CITIES_SUCCESS';
export const GET_ALL_CITIES_ERROR = 'GET_ALL_CITIES_ERROR';
