export const CREATE_ROUND_TRIP_SUCCESS = 'CREATE_ROUND_TRIP_SUCCESS';
export const CREATE_ROUND_TRIP_ERROR = 'CREATE_ROUND_TRIP_ERROR';

export const SPINNER_STATUS = 'SPINNER_STATUS';

export const GET_ALL_CITIES_SUCCESS = 'GET_ALL_CITIES_SUCCESS';
export const GET_ALL_CITIES_ERROR = 'GET_ALL_CITIES_ERROR';

export const AVAIL_REQUESTS_SUCCESS = 'AVAIL_REQUESTS_SUCCESS';
export const AVAIL_REQUESTS_ERROR = 'AVAIL_REQUESTS_ERROR';

export const AVAIL_SINGLE_REQUEST_SUCCESS = 'AVAIL_SINGLE_REQUEST_SUCCESS';
export const AVAIL_SINGLE_REQUEST_ERROR = 'AVAIL_SINGLE_REQUEST_ERROR';

export const APPROVE_REQUEST_SUCCESS = 'APPROVE_REQUEST_SUCCESS';
export const APPROVE_REQUEST_ERROR = 'APPROVE_REQUEST_ERROR';
