export const ONEWAY_SUCCESS = 'ONEWAY_SUCCESS';
export const ONEWAY_ERROR = 'ONEWAY_ERROR';
export const GET_CITY_SUCCESS = 'GET_CITY_SUCCESS';
export const GET_CITY_ERROR = 'GET_CITY_ERROR';
export const ONEWAY_INPUT = 'ONEWAY_INPUT';
export const UPDATE_SPINNER_STATUS = 'UPDATE_SPINNER_STATUS';
